---
title: "Quick learning curve estimation"
author: "Martin Schmettow"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Quick learning curve estimation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r}
library(tidyverse)
# devtools::install_github("schmettow/asymptote")
library(asymptote)
```

```{r}
Laptrain
```

```{r}
Laptrain %>% 
  filter(Part == "01") %>% 
  smoothary(perf = Duration, trial = trial)
```

```{r}
Laptrain %>% 
  filter(Part == "01") %>% 
  coefary(perf = Duration, trial = trial)
```

```{r}
Laptrain %>%
  group_split(Part) %>%
  map_df(smoothary, perf = Duration, trial = trial) %>%
  ggplot(aes(x = trial, y = predict_ARY, group = Part)) +
  geom_point(aes(y = Duration)) +
  geom_smooth(se = F) +
  facet_wrap(~Part)

```
```{r}
Laptrain %>%
  group_split(Part) %>%
  map_df(coefary, perf = Duration, trial = trial) %>% 
  knitr::kable()
```

